language: nix

env:
  - GHC_VERSION="7.8.4"
  - GHC_VERSION="7.10.3"
  - GHC_VERSION="8.0.2"
  - GHC_VERSION="8.2.1"

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - /nix/store

before_install:
  - nix-env -i stack

script:
  - nix-shell --argstr ghc-version $GHC_VERSION --run ci-script

notifications:
  email: false
