language: nix

env:
  global:
    - LC_ALL=en_US.UTF-8
  matrix:
    - STACK_YAML=stack-8.yaml
    - STACK_YAML=stack-9.yaml

cache:
  directories:
    - $HOME/.stack
    - /nix/store

before_install:
  - nix-env -i stack

script:
  - stack test --nix --no-terminal --stack-yaml $STACK_YAML

notifications:
  email: false
