name: partial-semigroup-test
version: 0.1.0.3
github: chris-martin/partial-semigroup

synopsis: |
  Testing utilities for the partial-semigroup package

description: |
  Testing utilities for the partial-semigroup package,
  notably property testing to check the PartialSemigroup
  axioms.

category: Algebra, Testing

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license: Apache-2.0
license-file: license.txt

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Test.PartialSemigroup

dependencies:
  - base >= 4.9 && < 4.10
  - hedgehog >= 0.5 && < 0.6
  - partial-semigroup >= 0.1 && <0.2
