name: partial-semigroup
version: 0.0.0.1
github: chris-martin/partial-semigroup

synopsis: |
  A partial binary associative operator.

description: |
  A partial semigroup is like a semigroup, but the
  operator is partial. We represent this in Haskell
  as a total function @appendMaybe :: a -> a -> Maybe a@.

category: Algebra

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license: Apache-2.0
license-file: license.txt

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Data.PartialSemigroup

dependencies:
  - base

tests:

  doctest:
    source-dirs: test
    main: doctest.hs
    ghc-options:
      - -threaded
    dependencies:
      - doctest

  hedgehog:
    source-dirs: test
    main: hedgehog.hs
    ghc-options:
      - -threaded
    dependencies:
      - hedgehog
      - partial-semigroup
      - partial-semigroup-test
